name: Test World 8 Staking Dapp

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup DFX
        uses: dfinity/setup-dfx@v1
      
      - name: Start local replica
        run: dfx start --background
      
      - name: Deploy canisters
        run: |
          dfx deploy
          # Configure canister IDs for testing
          echo "FRONTEND_CANISTER_ID=zksib-liaaa-aaaaf-qanva-cai" >> $GITHUB_ENV
          echo "PAYOUT_CANISTER_ID=zeqfj-qyaaa-aaaaf-qanua-cai" >> $GITHUB_ENV
          echo "WALLET_CANISTER_ID=rce3q-iaaaa-aaaap-qpyfa-cai" >> $GITHUB_ENV
      
      - name: Run tests
        run: |
          dfx canister call test_payout test_balance_management
          dfx canister call test_payout test_fee_management
          dfx canister call test_payout test_batch_processing
          dfx canister call test_payout test_full_payout_process
          dfx canister call test_payout test_error_recovery
          dfx canister call test_payout test_system_under_load
          dfx canister call test_payout test_system_stress
          dfx canister call test_payout test_access_control
          dfx canister call test_payout test_balance_protection
      
      - name: Stop local replica
        run: dfx stop 